### ISSUE TITLE
connection to localhost refused

### ISSUE THREAD

**Issue by narayan-iyengar** [jonlangemak/ansible_kubernetes#1]
Hi there,
   I am very new to kubernetes and tried following your post about using sensible to deploy a local cluster. Ansible playbook run completes with no errors, but when I try to get cluster-info or get pods, I get the following error:
`$kubectl get pods`
`The connection to the server localhost:8080 was refused - did you specify the right host or port`

Even if I do specify the --server option, I get a similar error. 

thanks for your help and excellent posts

**Comment by jonlangemak** [comment]
Sorry for the delay!  Are you trying to run kubectl from the master node?  If so - what does your API server config look like?  Specifically the systemd unit file for the service?

**Comment by narayan-iyengar** [comment]
Hi Jon,
  Thanks for getting back to me. As I mentioned I am new to k8s and here is what I was trying to do:
Setup a cluster on my two local ubuntu 16.04 machines. While reading on how to do that I came across the kubeadm page and started down that path. I was able to get a cluster up with kubeadm and then I stumbled on to your blog post about using ansible to deploy a k8s cluster. So I tore down my kubeadm setup and went with your repo...in doing so I got the cannot connect to server

Today I tore down kubeadm again and ran your playbook, and I get 
`Unable to connect to the server: x509: certificate signed by unknown authority`


Some questions:
is kubenet-plugin deprecated by kubernetes?
Is there a way to undo the ansible playbook and start from scratch?

Here is the systemd unit file for the api-server:
Description=Kubernetes API Server
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
ExecStart=/usr/bin/kube-apiserver \
  --admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota \
  --advertise-address=10.5.124.35 \
  --allow-privileged=true \
  --apiserver-count=3 \
  --authorization-mode=ABAC \
  --authorization-policy-file=/var/lib/kubernetes/authorization-policy.jsonl \
  --bind-address=0.0.0.0 \
  --enable-swagger-ui=true \
  --etcd-cafile=/var/lib/kube_certs/ca.pem \
  --insecure-bind-address=0.0.0.0 \
  --kubelet-certificate-authority=/var/lib/kube_certs/ca.pem \
  --etcd-servers=https://10.5.124.35:2379 \
  --service-account-key-file=/var/lib/kube_certs/kubernetes-key.pem \
  --service-cluster-ip-range=10.11.12.0/24 \
  --service-node-port-range=30000-32767 \
  --tls-cert-file=/var/lib/kube_certs/kubernetes.pem \
  --tls-private-key-file=/var/lib/kube_certs/kubernetes-key.pem \
  --token-auth-file=/var/lib/kubernetes/token.csv \
  --v=2
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

**Comment by jonlangemak** [comment]
So to clarify - are you attempting to run kubectl commands on the same server as the master?  What do the logs of the API-server tell you?

**Comment by jonlangemak** [comment]
Let me know if this is still happening.  Closing for now

**Comment by narayan-iyengar** [comment]
Apologies. Got side tracked...if I pick this back up  and still encounter it, I will let you know

thanks again
