### ISSUE TITLE
systemd_templatez/kube-controller-manager.service error

### ISSUE THREAD

**Issue by derwin4o** [jonlangemak/ansible_kubernetes#2]
Hi Jon, 
Thank you very much for the tutorial (http://www.dasblinkenlichten.com/getting-started-kubernetes-using-ansible/) , it Rocks... :) . 
Today I tried to reproduce it on my lab and everything was passing perfect, until i tried to find Pod networking allocation with:
 kubectl get nodes --output=jsonpath='{range .items[*]}{.status.addresses[?(@.type=="InternalIP")].address} {.spec.podCIDR} {"\n"}{end}' which failed.

I'm not sure but maybe files/systemd_templatez/kube-controller-manager.service
should be corrected with:
diff files/systemd_templatez/kube-controller-manager.service files/systemd_templatez/kube-controller-manager.service.orig

"+"   --allocate-node-cidrs=true \
"+"   --cluster-cidr={{ cluster_info.cluster_node_cidr }} \

"-"   --allocate-node-cidrs=false \

Regards,
Radoslav Mitov

**Comment by jonlangemak** [comment]
So did you get this sorted out?  I think it's likely an issue because Im in the process of upgrading the repo to use Calico networking.  The post on that has been delayed.  Sorry for the confusion!

**Comment by derwin4o** [comment]
Yes , with adding 
--allocate-node-cidrs=true 
--cluster-cidr={{ cluster_info.cluster_node_cidr }} 

instead of 
 --allocate-node-cidrs=false 
everything went perfect!

**Comment by jonlangemak** [comment]
Heres the updated documentation just to fully close this out...

http://www.dasblinkenlichten.com/getting-started-with-calico-on-kubernetes/
