### ISSUE TITLE
files/systemd_templatez/kubelet.service 

### ISSUE THREAD

**Issue by derwin4o** [jonlangemak/ansible_kubernetes#3]
Hi Jon, 
just found that if the networking should work as in the example from http://www.dasblinkenlichten.com/getting-started-kubernetes-using-ansible
The following changes should be applied in files/systemd_templatez/kubelet.service 
"+"   --network-plugin=kubenet \
"+"  --non-masquerade-cidr={{ cluster_info.cluster_node_cidr }} \

"-"  --network-plugin=cni

Regards,
Radoslav Mitov

**Comment by jonlangemak** [comment]
I made a comment on this one https://github.com/jonlangemak/ansible_kubernetes/issues/2.  Apologies I havent gotten the updated post out yet but I will shortly.  The updated repo uses Calico for networking so you need to deploy that manifest to the cluster before deploying pods.

**Comment by jonlangemak** [comment]
Whoops - I'll keep this open until I get the updated post out.

**Comment by jonlangemak** [comment]
Here's the updated documentation...

http://www.dasblinkenlichten.com/getting-started-with-calico-on-kubernetes/

Does this help?

**Comment by derwin4o** [comment]
Hi,
yes, yesterday I went thru the new post...Thank you very much for the
series, they are very helpful for me!
I was just wondering  why Calico has chosen full mesh bgp instead of route
reflection with Kubernetes controllers and what will happen with
Calico-node containers with 100 bgp sessions ...?

Regards,
Radoslav

2017-05-18 19:44 GMT+01:00 Jon Langemak <notifications@github.com>:

**Comment by jonlangemak** [comment]
There are lots of options with Calico in BGP.  Stay tuned for an upcoming post on that :)
