### ISSUE TITLE
etcd-0 bad certificate

### ISSUE THREAD

**Issue by dimthe** [jonlangemak/ansible_kubernetes#4]
hello 
can you giveme a hint why i get this bad cert error ?

kubectl get componentstatus
NAME                 STATUS      MESSAGE                                                                ERROR
scheduler            Healthy     ok                                                                     
controller-manager   Healthy     ok                                                                     
etcd-0               Unhealthy   Get https://host01:2379/health: remote error: tls: bad certificate

**Comment by jonlangemak** [comment]
What do your cert config files look like?  Default location is /var/lib/kube_certs.  Paste the output of pki_ca_config.json, pki_ca_csr.json, and pki_crt_csr.json

**Comment by jonlangemak** [comment]
No response so closing
