### ISSUE TITLE
Can't get out of the NotReady state

### ISSUE THREAD

**Issue by rsdrichard** [jonlangemak/ansible_kubernetes#6]
I tried everything, but IO can't get out of the NotReady state. 
However, kubectl get componentstatus is fine

I noticed some etcd errors. I also wonder if the older aAnsible cluster building  posting still works with the new Calico centric GitHub changes
Is it OK that calicoctl.cfg in the endpoints use the IP in etcdendpoint ?
/etc/cni was not created but it is referred to in /etc/calico/calicoctl.cfg

**Comment by jonlangemak** [comment]
Im missing what the problem is here.  Can you clarify the problem a little further?

**Comment by rsdrichard** [comment]
Went thru install a few times.
kubectl get componentstatus is fine. However, kubectl get nodes returns:


simon@k8s-1:~$ kubectl get nodes
NAME      STATUS     AGE       VERSION
k8s-2     NotReady   5d        v1.7.0
k8s-3     NotReady   5d        v1.7.0
k8s-4     NotReady   5d        v1.7.0
k8s-5     NotReady   5d        v1.7.0

When I do:
 kubectl describe node  I get the following error:

Jul 2017 09:06:21 -0700         KubeletNotReady                 runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

I also found that none of my minions have a /etc/cni directory

Thanks

**Comment by rsdrichard** [comment]
I got it now. I ran:
root@k8s-1:/var/lib/kubernetes/pod_defs# kubectl apply -f calico.yaml
after editing the calico.yaml file and my nodes are now in Ready state.

**Comment by rsdrichard** [comment]
Ignore the NotReady state until you run
root@k8s-1:/var/lib/kubernetes/pod_defs# kubectl apply -f calico.yaml
